### ISSUE TITLE
[2.80] Importing models with animations causes error

### ISSUE THREAD

**Issue by drewc5131** [rdb/blender-egg-importer#11]
When importing a model with animations (separate model files, selecting them both at the same time), it imports the model but without the animation and throws this error
```Traceback (most recent call last):
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\__init__.py", line 62, in execute
    root.build_tree(context)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1088, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1088, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1682, in build_tree
    self.skeleton.build_animations(context, self)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1662, in build_animations
    child.build_animations(context, bundle)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1662, in build_animations
    child.build_animations(context, bundle)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1660, in build_animations
    bundle.add_curves(context, self.name, child)
  File "C:\Users\Drew\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1773, in add_curves
    x_curve = fcurves.new(prefix + 'location', 0)
TypeError: ActionFCurves.new(): required parameter "index" to be a keyword argument!```

**Comment by rdb** [comment]
Thanks, fixed; I can import the animated Roaming Ralph model now.
