### ISSUE TITLE
TypeError exception in Blender 2.81

### ISSUE THREAD

**Issue by NickSparrow** [rdb/blender-egg-importer#12]
Hello there, I tried importing a .egg file that uses static meshes only.

Tho an error occurs when loading it in:
bpy.context.space_data.params.directory = "C:\\Users\\capnn\\Documents\\"
bpy.context.space_data.params.directory = "C:\\Users\\capnn\\Downloads\\"
Modules Installed (blender-egg-importer-master) from 'C:\\Users\\capnn\\Downloads\\blender-egg-importer-master.zip' into 'C:\\Users\\capnn\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
bpy.context.space_data.system_folders_active = 1
'' was renamed to 'Object' due to a name conflict
'' was renamed to 'Object.001' due to a name conflict
Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\__init__.py", line 62, in execute
    root.build_tree(context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1088, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1458, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1458, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1458, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  [Previous line repeated 4 more times]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1367, in build_tree
    data.update(calc_edges=True, calc_loop_triangles=True)
TypeError: Mesh.update(): was called with invalid keyword argument(s) (calc_loop_triangles), expected (calc_edges, calc_edges_loose)

location: <unknown location>:-1

This is the file I try to import:
[https://drive.google.com/open?id=1oQq-37ayUBpDhdANCDwJaCqgw1eVATXU](url)

I hope you can help.

King regards,
Nick

**Comment by NickSparrow** [comment]
I fixed it, I needed to use Blender 2.79B

**Comment by rdb** [comment]
Apparently the `calc_loop_triangles` argument was removed in Blender 2.81.  I'll check in a fix.
