### ISSUE TITLE
[2.82a] default pose + animation - AtrributeError 

### ISSUE THREAD

**Issue by BartGunshot** [rdb/blender-egg-importer#13]
Try to import model that has a default pose along with an animation file. Model imports with armature unparented and throws this error:
```Traceback (most recent call last):
  File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\__init__.py", line 62, in execute
    root.build_tree(context)
  File "C:\Users\Thomas\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1088, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1088, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1694, in build_tree
    self.skeleton.build_animations(context, self)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1674, in build_animations
    child.build_animations(context, bundle)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1674, in build_animations
    child.build_animations(context, bundle)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1674, in build_animations
    child.build_animations(context, bundle)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1672, in build_animations
    bundle.add_curves(context, self.name, child)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\blender-egg-importer-master\importer.py", line 1782, in add_curves
    matrices[i] = context.transform_matrix(matmul(joint_matrix.inverted(), m))
AttributeError: 'NoneType' object has no attribute 'inverted'

location: <unknown location>:-1
```
I don't have that many models to test unfortunately, but it seems like it only affects those with default poses. Can provide the model if needed.

**Comment by rdb** [comment]
Please do share the model, thanks.  If sensitive, email it to ![image](https://user-images.githubusercontent.com/194842/79968607-a8c71d80-8490-11ea-8d17-01d84fb7e58a.png)

**Comment by BartGunshot** [comment]
Sent you an email with attached model files. Thanks!

**Comment by rdb** [comment]
Should be fixed now.
