### ISSUE TITLE
Error Importing 2.79 & 2.83

### ISSUE THREAD

**Issue by CapnNickSparrow** [rdb/blender-egg-importer#15]
Hello,
trying to import .eggs, all of them work except one:
```

Read prefs: C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\config\userpref.blend
AL lib: (EE) SetChannelMap: Failed to match front-center channel (2) in channel map
found bundled python: C:\Program Files\Blender Foundation\Blender 2.83\2.83\python
Warning: class IMPORT_SCENE_OT_egg contains a property which should be an annotation!
C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py:86
    assign as a type annotation: IMPORT_SCENE_OT_egg.filter_glob
    assign as a type annotation: IMPORT_SCENE_OT_egg.directory
    assign as a type annotation: IMPORT_SCENE_OT_egg.files
    assign as a type annotation: IMPORT_SCENE_OT_egg.load_external
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py", line 58, in execute
    root = context.read_file(path)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
    parse_egg(buffer, root, self)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 2 more times]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1244, in end_child
    vpool = context.vertex_pools[child.pool]
AttributeError: pool

location: <unknown location>:-1

location: <unknown location>:-1

```

Any idea what this means?

**Comment by rdb** [comment]
Please attach or email egg file.

**Comment by CapnNickSparrow** [comment]
[pir_m_are_bui_ravensCove.zip](https://github.com/rdb/blender-egg-importer/files/5146788/pir_m_are_bui_ravensCove.zip)

**Comment by rdb** [comment]
Your .egg file has an empty `<Polygon>` at line 1765877.  I think that's invalid, but I'll change the importer to ignore these with a warning instead of raising an error.

I'll also improve the error reporting to show a line number where the error happens (so that it's easier to find these issues yourself).

**Comment by CapnNickSparrow** [comment]
Did fix that bug, but it opened a new error:
`Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py", line 58, in execute
    root = context.read_file(path)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
    buffer = io.StringIO(data)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 2 more times]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1244, in end_child
    # This indicates the root of an animated model.
AttributeError: pool

location: <unknown location>:-1
`
I found some more, they say something about a Mat Struct, not sure what I will send those as well for analysis:

Kingshead: 
[pir_m_are_isl_kingshead.zip](https://github.com/rdb/blender-egg-importer/files/5146941/pir_m_are_isl_kingshead.zip)
`
Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py", line 58, in execute
    root = context.read_file(path)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
    buffer = io.StringIO(data)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 1 more time]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
    elif type == 'BILLBOARDCENTER':
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
    mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: <unknown location>:-1
`

Bilgewater 
[pir_m_are_isl_bilgewater.zip](https://github.com/rdb/blender-egg-importer/files/5146940/pir_m_are_isl_bilgewater.zip)
`
Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py", line 58, in execute
    root = context.read_file(path)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
    buffer = io.StringIO(data)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 2 more times]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
    elif type == 'BILLBOARDCENTER':
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
    mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: <unknown location>:-1
`

Madre
[pir_m_are_isl_madre_del_fuego.zip](https://github.com/rdb/blender-egg-importer/files/5146944/pir_m_are_isl_madre_del_fuego.zip)
`
Traceback (most recent call last):
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\__init__.py", line 58, in execute
    root = context.read_file(path)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
    buffer = io.StringIO(data)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 1 more time]
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
    elif type == 'BILLBOARDCENTER':
  File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
    mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: <unknown location>:-1
`

I hope these will help
