### ISSUE TITLE
More errors while converting on 2.79 & 2.83

### ISSUE THREAD

**Issue by CapnNickSparrow** [rdb/blender-egg-importer#16]
Hello there,
It did fix that bug in #15 , but it opened a new error:
[pir_m_are_bui_ravensCove.zip](https://github.com/rdb/blender-egg-importer/files/5146950/pir_m_are_bui_ravensCove.zip)

`Traceback (most recent call last):
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master_init_.py", line 58, in execute
root = context.read_file(path)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
buffer = io.StringIO(data)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
_parse_egg_element(fp, visitor, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
[Previous line repeated 2 more times]
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
visitor.end_child(context, type, name, child)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1244, in end_child
# This indicates the root of an animated model.
AttributeError: pool

location: :-1
`
**I found some more files that give errors, they say something about a Mat Struct, not sure what I will send those as well for analysis:**

Kingshead:
[pir_m_are_isl_kingshead.zip](https://github.com/rdb/blender-egg-importer/files/5146948/pir_m_are_isl_kingshead.zip)

`
Traceback (most recent call last):
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master_init_.py", line 58, in execute
root = context.read_file(path)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
buffer = io.StringIO(data)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
_parse_egg_element(fp, visitor, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
[Previous line repeated 1 more time]
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
visitor.end_child(context, type, name, child)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
elif type == 'BILLBOARDCENTER':
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: :-1
`

Bilgewater
[pir_m_are_isl_bilgewater.zip](https://github.com/rdb/blender-egg-importer/files/5146953/pir_m_are_isl_bilgewater.zip)

`
Traceback (most recent call last):
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master_init_.py", line 58, in execute
root = context.read_file(path)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
buffer = io.StringIO(data)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
_parse_egg_element(fp, visitor, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
[Previous line repeated 2 more times]
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
visitor.end_child(context, type, name, child)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
elif type == 'BILLBOARDCENTER':
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: :-1
`

Madre
[pir_m_are_isl_madre_del_fuego.zip](https://github.com/rdb/blender-egg-importer/files/5146956/pir_m_are_isl_madre_del_fuego.zip)

`
Traceback (most recent call last):
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master_init_.py", line 58, in execute
root = context.read_file(path)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 74, in read_file
buffer = io.StringIO(data)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
_parse_egg_element(fp, visitor, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
_parse_egg_element(fp, child, context)
[Previous line repeated 1 more time]
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
visitor.end_child(context, type, name, child)
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1254, in end_child
elif type == 'BILLBOARDCENTER':
File "C:\Users\capnn\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\blender-egg-importer-master\importer.py", line 1358, in add_polygon
mesh.uv_textures.new(name)
ReferenceError: StructRNA of type Material has been removed

location: :-1
`

I hope these will help

**Comment by rdb** [comment]
Please update to the latest version of blender-egg-importer.  You're using a very old version.

**Comment by CapnNickSparrow** [comment]
Oh my bad, Blender doesn't auto replace, I had to remove it and reinstall it and it indeed works! Thank you very much!

**Comment by rdb** [comment]
For the record, I've also sporadically gotten the message "StructRNA of type Material has been removed".  It may be a bug in Blender.  What usually fixes it for me is shutting down and reopening Blender, and making sure I have created a new and empty scene to import into.
