### ISSUE TITLE
Error when importing 2.90.0

### ISSUE THREAD

**Issue by SankaDaVinci** [rdb/blender-egg-importer#17]
This is my traceback

Encountered KeyError at line 1306468 of pir_m_are_bui_portRoyal.egg: 'bpy_prop_collection[key]: key "" not found'

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\__init__.py", line 59, in execute
    root = context.read_file(path)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 80, in read_file
    parse_egg(buffer, root, self)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  [Previous line repeated 4 more times]
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1298, in end_child
    other = bpy.data.meshes[self.name]
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

**Comment by rdb** [comment]
This happens when you have unnamed `<Group>`s in the .egg file.  Fixed now.
