### ISSUE TITLE
ReferenceError: StructRNA of type Mesh has been removed

### ISSUE THREAD

**Issue by SankaDaVinci** [rdb/blender-egg-importer#18]
About the groups is fixed, but now there is this weird traceback coming from the importer itself

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\__init__.py", line 63, in execute
    root.build_tree(context)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1136, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  [Previous line repeated 2 more times]
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1427, in build_tree
    data.update(calc_edges=True)
ReferenceError: StructRNA of type Mesh has been removed

location: <unknown location>:-1

**Comment by rdb** [comment]
Try closing and reopening Blender and creating a new scene file to import into.

**Comment by SankaDaVinci** [comment]
Still getting the same thing

bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 3 object(s)
'' was renamed to 'Object' due to a name conflict
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\__init__.py", line 63, in execute
    root.build_tree(context)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1136, in build_tree
    child.build_tree(context, parent, inv_matrix, under_dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1523, in build_tree
    child.build_tree(context, object, inv_matrix, under_dart or self.dart)
  [Previous line repeated 2 more times]
  File "C:\Users\danie\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-egg-importer-master\importer.py", line 1427, in build_tree
    data.update(calc_edges=True)
ReferenceError: StructRNA of type Mesh has been removed

location: <unknown location>:-1

**Comment by rdb** [comment]
OK, I think I fixed it now.  Blender is under some circumstances removing the mesh before it is assigned to an object.

**Comment by R1ezz** [comment]
@rdb 

Could you possibly share your fix for this issue.

I am sitting with the same issue at the moment.
