### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by S00pergang** [rdb/blender-egg-importer#28]
Getting an error when I import a egg file

`Traceback (most recent call last):
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\__init__.py", line 59, in execute
    root = context.read_file(path)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 80, in read_file
    parse_egg(buffer, root, self)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1351, in end_child
    self.add_polygon(context, child, vpool)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 1451, in add_polygon
    bmat = prim.material.get_material(self, prim)
  File "[REDACTED]\Blender Foundation\Blender\2.80\scripts\addons\blender-egg-importer-master\importer.py", line 436, in _get_material_28
    bmat.ior = self.ior
AttributeError: 'Material' object has no attribute 'ior'

location: <unknown location>:-1

`

I am using blender 2.80 and the addon is version 1.8

**Comment by S00pergang** [comment]
Ah, nvm, wrong blender ver....

**Comment by S00pergang** [comment]
Actually, got an error importing a specific egg
`Encountered AttributeError at line 11485 of ttcc_ene_chainsaw-zero.egg: 'Material' object has no attribute 'ior'
Traceback (most recent call last):
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\__init__.py", line 59, in execute
    root = context.read_file(path)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 80, in read_file
    parse_egg(buffer, root, self)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\eggparser.py", line 64, in parse_egg
    _parse_egg_element(fp, visitor, context)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\eggparser.py", line 141, in _parse_egg_element
    _parse_egg_element(fp, child, context)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\eggparser.py", line 148, in _parse_egg_element
    visitor.end_child(context, type, name, child)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1351, in end_child
    self.add_polygon(context, child, vpool)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 1451, in add_polygon
    bmat = prim.material.get_material(self, prim)
  File "[REDACTED]\Blender Foundation\Blender\2.81\scripts\addons\blender-egg-importer-master\importer.py", line 436, in _get_material_28
    bmat.ior = self.ior
AttributeError: 'Material' object has no attribute 'ior'

location: <unknown location>:-1

`
https://files.catbox.moe/8s06kg.egg

**Comment by ghost** [comment]
I actually forgot to mention that I switched to blender 2.79 and it started working. Guess 2.8+ ain't that ready

**Comment by rdb** [comment]
Note that I fixed this yesterday...

**Comment by ghost** [comment]
> Note that I fixed this yesterday...

Do you know the latest working setup (blender ver and addon ver)

**Comment by S00pergang** [comment]
Also the blender 2.79 version won't import animation, it's blank.

**Comment by ghost** [comment]
Animations won't port, it's just blank, using the latest plugin ver and blender 2.81

**Comment by ghost** [comment]
It's behaving weird, it only imports things once, but then throws errors at me when i try to import again with animations
